"""fix payment-order one-to-one relation

Revision ID: 35a39a232a47
Revises: 51c2dec9b4f1
Create Date: 2026-05-30 09:22:36.580553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a39a232a47'
down_revision: Union[str, Sequence[str], None] = '51c2dec9b4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_payment_id'), table_name='orders')
    op.drop_constraint(op.f('orders_payment_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_id')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_payment_id_fkey'), 'orders', 'payments', ['payment_id'], ['id'])
    op.create_index(op.f('ix_orders_payment_id'), 'orders', ['payment_id'], unique=False)
    # ### end Alembic commands ###
