"""delete user relationship from carts table

Revision ID: ae995e7ce37f
Revises: e1f47af9ae93
Create Date: 2026-05-30 06:13:12.652616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae995e7ce37f'
down_revision: Union[str, Sequence[str], None] = 'e1f47af9ae93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
