"""remove payment_id from orders

Revision ID: b6043d503a6a
Revises: bfb7eae50825
Create Date: 2026-06-09 10:57:43.656599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6043d503a6a'
down_revision: Union[str, Sequence[str], None] = 'bfb7eae50825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_payment_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_payment_id_fkey'), 'orders', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###
