"""add payment_id to orders

Revision ID: bfb7eae50825
Revises: 43666ecea413
Create Date: 2026-06-08 19:11:00.662887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb7eae50825'
down_revision: Union[str, Sequence[str], None] = '43666ecea413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
