"""update variant_id from attributes table

Revision ID: ddf242299a42
Revises: 976eeff6480d
Create Date: 2026-07-01 14:17:35.425911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf242299a42'
down_revision: Union[str, Sequence[str], None] = '976eeff6480d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attributes_variant_id_fkey'), 'attributes', type_='foreignkey')
    op.create_foreign_key(None, 'attributes', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.create_foreign_key(op.f('attributes_variant_id_fkey'), 'attributes', 'product_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###
