"""add cascade to order address

Revision ID: fa3fff768272
Revises: e5b2bcba1b28
Create Date: 2026-06-24 15:08:14.973215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3fff768272'
down_revision: Union[str, Sequence[str], None] = 'e5b2bcba1b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_addresses', ['order_id'])
    op.drop_constraint(op.f('order_addresses_order_id_fkey'), 'order_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'order_addresses', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_addresses', type_='foreignkey')
    op.create_foreign_key(op.f('order_addresses_order_id_fkey'), 'order_addresses', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_addresses', type_='unique')
    # ### end Alembic commands ###
